# Numpy Array

In [1]:
import numpy as np
type(np.array(["vbhvh", 2, 3]))

numpy.ndarray

In [2]:
l = [1,2,3,4,5,6]
type(l)

list

In [3]:
np.array(l)

array([1, 2, 3, 4, 5, 6])

In [5]:
type(np.array(l))

numpy.ndarray

### Upcasting

In [6]:
np.array([1, 2, 3.0])

array([1., 2., 3.])

In [8]:
np.array([2,7,'abcd', 4.5,50.56, True])  # change everyhting in string( U11)

array(['2', '7', 'abcd', '4.5', '50.56', 'True'], dtype='<U11')

### two dimensions

In [15]:
n = np.array([[1, 2], [3, 4]])
n

array([[1, 2],
       [3, 4]])

In [14]:
n.ndim

2

In [16]:
#Minimum dimensions 2

In [17]:
np.array([1,2,3])

array([1, 2, 3])

In [18]:
np.array([1, 2, 3], ndmin=5)

array([[[[[1, 2, 3]]]]])

In [19]:
#dtype

In [20]:
 np.array([1, 2, 3], dtype=complex)

array([1.+0.j, 2.+0.j, 3.+0.j])

### Data-type consisting of more than one element:

In [22]:
x = np.array([(1,2),(3,4)],dtype=[('a','<i2'),('b','<i8')])  # in numpy- int16, int32, int64
x

array([(1, 2), (3, 4)], dtype=[('a', '<i2'), ('b', '<i8')])

In [24]:
type(x[0][0])

numpy.int16

In [25]:
type(x[0][1])

numpy.int64

In [26]:
type(x[1][0])

numpy.int16

In [13]:

# Matrix is sub-class of an array

In [27]:
np.mat(np.array([[1, 2],[4,7]]))

matrix([[1, 2],
        [4, 7]])

In [30]:
type(np.mat(np.array([[1, 2],[4,7]])))

numpy.matrix

In [32]:
m = np.mat(np.array([[1, 2],[4,7]]))
m

matrix([[1, 2],
        [4, 7]])

In [34]:
m[0]

matrix([[1, 2]])

In [35]:
m[1]

matrix([[4, 7]])

In [37]:
m[0][0]

matrix([[1, 2]])

In [38]:
m[0,0]

1

In [39]:
m[1,1]

7

In [40]:
m[0][0,1]

2

In [41]:
np.array([[1, 2],[4,7]])

array([[1, 2],
       [4, 7]])

In [42]:
type(np.array([[1, 2],[4,7]]))

numpy.ndarray

In [43]:
np.mat('1 2; 3 4') # rarely use

matrix([[1, 2],
        [3, 4]])

# numpy.asarray

In [44]:
#Convert the input to an array.

In [45]:
#Convert a list into an array:

In [46]:
 a = [1, 2]
type(a)

list

In [47]:
np.asarray(a)

array([1, 2])

In [48]:
type(np.asarray(a))

numpy.ndarray

In [49]:
np.asanyarray(a) # asanyarray

array([1, 2])

In [50]:
type(np.asanyarray(a))

numpy.ndarray

* array
* asarray
* asanyarray

All three converts or data into an array but the difference is asanyarray not converts if it is already present into some
kind of array.

In [51]:
# numpy.copy

In [53]:
a = np.array([1,2,3,4,5])
a

array([1, 2, 3, 4, 5])

In [54]:
b=a           # they share same location   ## shaloow copy

In [55]:
b

array([1, 2, 3, 4, 5])

In [56]:
b[0]

1

In [59]:
b[0]= 100
b

array([100,   2,   3,   4,   5])

In [60]:
a

array([100,   2,   3,   4,   5])

In [61]:
c = np.array(a,copy=True)
c                              # deep copy

array([100,   2,   3,   4,   5])

In [62]:
c[0]

100

In [64]:
c[0]= 50
c                 # share different location

array([50,  2,  3,  4,  5])

In [65]:
a

array([100,   2,   3,   4,   5])

In [66]:
#If dtype is set, array is copied only if dtype does not match:

In [67]:
a = np.array([1, 2], dtype=np.float32)
a

array([1., 2.], dtype=float32)

In [68]:
np.asarray([1,2]) is a

False

In [69]:
np.asarray([1,2])

array([1, 2])

In [70]:
np.asarray(a, dtype=np.float64) is a

False

In [71]:
# ndarray subclasses are not passed through

In [72]:
issubclass(np.matrix, np.ndarray)

True

In [73]:
a = np.matrix([[1, 2]])
np.asanyarray(a)


matrix([[1, 2]])

In [74]:
np.asarray(a) is a

False

In [75]:
np.asanyarray(a) is a

True

In [51]:
type(np.asarray(a))

numpy.ndarray

# numpy.asanyarray

In [76]:
a = [1, 2]
np.asanyarray(a)

array([1, 2])

In [77]:
a = np.matrix([1, 2])
a

matrix([[1, 2]])

In [78]:
np.asanyarray([1,2]) is a

False

In [79]:
np.array(a, copy=True)  

array([[1, 2]])

In [80]:
#Create an array x, with a reference y and a copy z:

In [82]:
x = np.array([1, 2, 3])
x


array([1, 2, 3])

In [83]:
y = x

In [84]:
z = np.copy(x)

In [85]:
y[0] = 100
x

array([100,   2,   3])

In [86]:
x

array([100,   2,   3])

In [89]:
y

array([100,   2,   3])

In [87]:
id(x[0])

2088005283184

In [88]:
id(y[0])

2088005283280

In [90]:
id(x) 

2088005178912

In [91]:
id(y)

2088005178912

In [92]:
id(x[1])

2088005283312

In [93]:
id(y[1])

2088005283472

# numpy.fromfunction

Construct an array by executing a function over each coordinate.

In [94]:
np.fromfunction(lambda i, j: i == j, (3, 3), dtype=int)

array([[ True, False, False],
       [False,  True, False],
       [False, False,  True]])

In [95]:
np.fromfunction(lambda i, j: i + j, (3, 3), dtype=int)

array([[0, 1, 2],
       [1, 2, 3],
       [2, 3, 4]])

In [96]:
np.fromfunction(lambda i, j: i / j, (3, 3), dtype=int)

<ipython-input-96-913a1569dac7>:1: RuntimeWarning: divide by zero encountered in true_divide
  np.fromfunction(lambda i, j: i / j, (3, 3), dtype=int)
<ipython-input-96-913a1569dac7>:1: RuntimeWarning: invalid value encountered in true_divide
  np.fromfunction(lambda i, j: i / j, (3, 3), dtype=int)


array([[nan, 0. , 0. ],
       [inf, 1. , 0.5],
       [inf, 2. , 1. ]])

In [99]:
a =np.fromfunction(lambda i, j, k: i + j +k, (3, 3, 3), dtype=int) # 3 array 3 row 3 col
a

array([[[0, 1, 2],
        [1, 2, 3],
        [2, 3, 4]],

       [[1, 2, 3],
        [2, 3, 4],
        [3, 4, 5]],

       [[2, 3, 4],
        [3, 4, 5],
        [4, 5, 6]]])

In [100]:
a[2]

array([[2, 3, 4],
       [3, 4, 5],
       [4, 5, 6]])

In [101]:
a[2][2]

array([4, 5, 6])

In [102]:
a[2][2,2]

6

In [103]:
a[2][2][2]

6

In [105]:
def test(i,j,k):
    return i+j+k
a = np.fromfunction(test, (3, 3, 3), dtype=int)
a

array([[[0, 1, 2],
        [1, 2, 3],
        [2, 3, 4]],

       [[1, 2, 3],
        [2, 3, 4],
        [3, 4, 5]],

       [[2, 3, 4],
        [3, 4, 5],
        [4, 5, 6]]])

### Create a new 1-dimensional array from an iterable object.

In [106]:
l= [1,2,3,4,5,6]
for i in l:
    print(i)

1
2
3
4
5
6


In [111]:
iterable = (x*x for x in range(5))
iterable

<generator object <genexpr> at 0x000001E626D3FEB0>

In [108]:
np.fromiter(iterable, float)

array([ 0.,  1.,  4.,  9., 16.])

In [112]:
np.fromiter(iterable, int)

array([ 0,  1,  4,  9, 16])

In [113]:
#A new 1-D array initialized from text data in a string

In [114]:
a = np.fromstring('234 234',sep=' ')
a

array([234., 234.])

In [115]:
np.fromstring('1, 2', dtype=int, sep=',')

array([1, 2])

### How to create create a record array from a (flat) list of arrays

In [116]:
x1=np.array([1,2,3,4])

In [117]:
x2=np.array(['a','dd','xyz','12'])

In [118]:
x3=np.array([1.1,2,3,4])
x4=np.array([1.1,2,3,4])
type(x4)

numpy.ndarray

In [119]:
r = np.core.records.fromarrays([x1,x2,x3,x4])
r

rec.array([(1, 'a', 1.1, 1.1), (2, 'dd', 2. , 2. ), (3, 'xyz', 3. , 3. ),
           (4, '12', 4. , 4. )],
          dtype=[('f0', '<i4'), ('f1', '<U3'), ('f2', '<f8'), ('f3', '<f8')])

In [120]:
r = np.core.records.fromarrays([x1,x2,x3,x4],names='a,b,c,d')
r

rec.array([(1, 'a', 1.1, 1.1), (2, 'dd', 2. , 2. ), (3, 'xyz', 3. , 3. ),
           (4, '12', 4. , 4. )],
          dtype=[('a', '<i4'), ('b', '<U3'), ('c', '<f8'), ('d', '<f8')])

In [121]:
r[1][1]

'dd'

In [122]:
r[1]["b"]

'dd'

In [123]:
print(r[1]["a"])

2


# data types

In [125]:
my_list = [1,2,3]
arr = np.array(my_list)
print("Type/Class of this object:",type(arr))
print("Here is the vector\n--------------------\n",arr)

Type/Class of this object: <class 'numpy.ndarray'>
Here is the vector
--------------------
 [1 2 3]


In [126]:
l= [2,3,4,5,6]
a = np.array(l)
a

array([2, 3, 4, 5, 6])

In [127]:
b = np.array([[3,4,5],[7,8,9]])
b

array([[3, 4, 5],
       [7, 8, 9]])

In [128]:
a.ndim

1

In [129]:
a.size

5

In [130]:
b.ndim

2

In [131]:
b.size

6

In [132]:
b.shape

(2, 3)

In [133]:
a.shape

(5,)

In [134]:
a.dtype

dtype('int32')

In [135]:
b.dtype

dtype('int32')

In [136]:
my_mat = [[1,2,3],[4,5,6],[7,8,9]]
mat = np.array(my_mat)
print("Type/Class of this object:",type(mat))
print("Here is the matrix\n----------\n",mat,"\n----------")
print("Dimension of this matrix: ",mat.ndim,sep='') #ndim gives the dimensison, 2 for a matrix, 1 for a vector
print("Size of this matrix: ", mat.size,sep='') #size gives the total number of elements
print("Shape of this matrix: ", mat.shape,sep='') #shape gives the number of elements along each axes (dimension)
print("Data type of this matrix: ", mat.dtype,sep='') #dtype gives the data type contained in the array


Type/Class of this object: <class 'numpy.ndarray'>
Here is the matrix
----------
 [[1 2 3]
 [4 5 6]
 [7 8 9]] 
----------
Dimension of this matrix: 2
Size of this matrix: 9
Shape of this matrix: (3, 3)
Data type of this matrix: int32


In [137]:
my_mat = [[1.1,2,3],[4,5.2,6],[7,8.3,9]]
mat = np.array(my_mat)
print("Data type of the modified matrix: ", mat.dtype,sep='') #dtype gives the data type contained in the array
print("\n\nEven tuples can be converted to ndarrays...")


Data type of the modified matrix: float64


Even tuples can be converted to ndarrays...


In [138]:
b = np.array([(1.5,2,3), (4,5,6)])
print("We write b = np.array([(1.5,2,3), (4,5,6)])")
print("Matrix made from tuples, not lists\n---------------------------------------")
print(b)

We write b = np.array([(1.5,2,3), (4,5,6)])
Matrix made from tuples, not lists
---------------------------------------
[[1.5 2.  3. ]
 [4.  5.  6. ]]


# arange and linspace

In [139]:
list(range(5))

[0, 1, 2, 3, 4]

In [140]:
np.arange(5)

array([0, 1, 2, 3, 4])

In [141]:
list(range(0,6,0.2))

TypeError: 'float' object cannot be interpreted as an integer

In [142]:
np.arange(0,6,0.2)

array([0. , 0.2, 0.4, 0.6, 0.8, 1. , 1.2, 1.4, 1.6, 1.8, 2. , 2.2, 2.4,
       2.6, 2.8, 3. , 3.2, 3.4, 3.6, 3.8, 4. , 4.2, 4.4, 4.6, 4.8, 5. ,
       5.2, 5.4, 5.6, 5.8])

In [143]:
print("A series of numbers:",type(np.arange(5,16)))
np.arange(5,16,2.3)# A series of numbers from low to high

A series of numbers: <class 'numpy.ndarray'>


array([ 5. ,  7.3,  9.6, 11.9, 14.2])

In [144]:
list(range(5,16,2))

[5, 7, 9, 11, 13, 15]

In [145]:
list(range(50,-1,5))

[]

In [146]:
print("Numbers spaced apart by 2:",np.arange(50,-1,5)) # Numbers spaced apart by 2

Numbers spaced apart by 2: []


In [147]:
print("Numbers spaced apart by float:",np.arange(0,11,2.5)) # Numbers spaced apart by 2.5

Numbers spaced apart by float: [ 0.   2.5  5.   7.5 10. ]


In [148]:
print("Every 5th number from 50 in reverse order\n",np.arange(5.0,-1,-5))

Every 5th number from 50 in reverse order
 [5. 0.]


In [149]:
np.linspace(0,100,10)

array([  0.        ,  11.11111111,  22.22222222,  33.33333333,
        44.44444444,  55.55555556,  66.66666667,  77.77777778,
        88.88888889, 100.        ])

In [150]:
print("21 linearly spaced numbers between 1 and 5\n--------------------------------------------")
print((np.linspace(1,5,50)))

21 linearly spaced numbers between 1 and 5
--------------------------------------------
[1.         1.08163265 1.16326531 1.24489796 1.32653061 1.40816327
 1.48979592 1.57142857 1.65306122 1.73469388 1.81632653 1.89795918
 1.97959184 2.06122449 2.14285714 2.2244898  2.30612245 2.3877551
 2.46938776 2.55102041 2.63265306 2.71428571 2.79591837 2.87755102
 2.95918367 3.04081633 3.12244898 3.20408163 3.28571429 3.36734694
 3.44897959 3.53061224 3.6122449  3.69387755 3.7755102  3.85714286
 3.93877551 4.02040816 4.10204082 4.18367347 4.26530612 4.34693878
 4.42857143 4.51020408 4.59183673 4.67346939 4.75510204 4.83673469
 4.91836735 5.        ]


# Matrix creation

In [2]:
import numpy as np
print("Vector of zeroes\n---------------------")
print(np.zeros(5))

Vector of zeroes
---------------------
[0. 0. 0. 0. 0.]


In [3]:
print("Matrix of zeroes\n--------------------")
print(np.zeros((3,4))) # Notice Tuples

Matrix of zeroes
--------------------
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [4]:
print("Vector of ones\n---------------------")
print(np.ones(5))

Vector of ones
---------------------
[1. 1. 1. 1. 1.]


In [5]:
print("Matrix of ones\n---------------------")
print(np.ones((5,2,8))) # Note matrix dimension specified by Tuples


Matrix of ones
---------------------
[[[1. 1. 1. 1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1. 1. 1. 1.]]

 [[1. 1. 1. 1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1. 1. 1. 1.]]

 [[1. 1. 1. 1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1. 1. 1. 1.]]

 [[1. 1. 1. 1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1. 1. 1. 1.]]

 [[1. 1. 1. 1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1. 1. 1. 1.]]]


In [6]:
print("Matrix of 5's\n---------------------")
print(5+np.ones((3,5)))

Matrix of 5's
---------------------
[[6. 6. 6. 6. 6.]
 [6. 6. 6. 6. 6.]
 [6. 6. 6. 6. 6.]]


In [7]:
print("Empty matrix\n-------------\n", np.empty((3,5)))

Empty matrix
-------------
 [[6. 6. 6. 6. 6.]
 [6. 6. 6. 6. 6.]
 [6. 6. 6. 6. 6.]]


In [8]:
mat1 = np.eye(4) 
print("Identity matrix of dimension", mat1.shape)
print(mat1)

Identity matrix of dimension (4, 4)
[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [9]:
np.arange(3)

array([0, 1, 2])

In [10]:
np.arange(3.0)

array([0., 1., 2.])

In [11]:
 np.arange(3,7)

array([3, 4, 5, 6])

In [12]:
np.arange(3,7,2)

array([3, 5])

In [13]:
np.linspace(2.0, 3.0, num=5)

array([2.  , 2.25, 2.5 , 2.75, 3.  ])

In [14]:
np.linspace(2.0, 3.0, num=5, endpoint=False)

array([2. , 2.2, 2.4, 2.6, 2.8])

In [15]:
np.linspace(2.0, 3.0, num=9, retstep=True)

(array([2.   , 2.125, 2.25 , 2.375, 2.5  , 2.625, 2.75 , 2.875, 3.   ]), 0.125)

In [16]:
#Return numbers spaced evenly on a log scale.
np.linspace(2.0, 3.0, num=4)

array([2.        , 2.33333333, 2.66666667, 3.        ])

In [17]:
np.logspace(2.0, 3.0, num=4,base = 10)

array([ 100.        ,  215.443469  ,  464.15888336, 1000.        ])

In [18]:
np.logspace(2.0, 3.0, num=4, endpoint=False)

array([100.        , 177.827941  , 316.22776602, 562.34132519])

In [19]:
np.logspace(2.0, 3.0, num=4, base=2.0)

array([4.        , 5.0396842 , 6.34960421, 8.        ])

### Extract a diagonal or construct a diagonal array.

In [21]:
x = np.arange(16).reshape((-1,4)) # detect automatically -1 as 4

In [22]:
x

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [23]:
np.arange(16).reshape(4,4)

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [24]:
np.diag(x)

array([ 0,  5, 10, 15])

In [25]:
np.diag(x, k=0
       )

array([ 0,  5, 10, 15])

In [26]:
np.diag(x, k=1)

array([ 1,  6, 11])

In [27]:
np.diag(x, k=2)

array([2, 7])

In [28]:
np.diag(x, k=3)

array([3])

In [29]:
np.diag(x, k=-1)

array([ 4,  9, 14])

In [30]:
np.diag(np.diag(x))

array([[ 0,  0,  0,  0],
       [ 0,  5,  0,  0],
       [ 0,  0, 10,  0],
       [ 0,  0,  0, 15]])

In [32]:
a = np.arange(18).reshape(3,6)
a

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17]])

In [36]:
np.diag(a, k=0)

array([ 0,  7, 14])

In [37]:
np.diag(a, k=1)

array([ 1,  8, 15])

In [46]:
np.diag(a, k=-1)  # take first sq matrix

array([ 6, 13])

In [39]:
np.diag(a, k=-2)

array([12])

In [40]:
np.diag(a, k=-3)

array([], dtype=int32)

### Create a two-dimensional array with the flattened input as a diagonal.

In [41]:
np.diagflat([[1,2], [3,4]])

array([[1, 0, 0, 0],
       [0, 2, 0, 0],
       [0, 0, 3, 0],
       [0, 0, 0, 4]])

In [42]:
np.diagflat([1,2], 1)

array([[0, 1, 0],
       [0, 0, 2],
       [0, 0, 0]])

### An array with ones at and below the given diagonal and zeros elsewhere.

In [43]:
np.tri(3, 5, 1, dtype=int)

array([[1, 1, 0, 0, 0],
       [1, 1, 1, 0, 0],
       [1, 1, 1, 1, 0]])

In [44]:
np.tri(3,5,2)

array([[1., 1., 1., 0., 0.],
       [1., 1., 1., 1., 0.],
       [1., 1., 1., 1., 1.]])

In [45]:
np.tri(3, 5,k=-1)

array([[0., 0., 0., 0., 0.],
       [1., 0., 0., 0., 0.],
       [1., 1., 0., 0., 0.]])

In [47]:
#return a Lower triangle of an array.

In [51]:
np.tril([[1,2,3],[4,5,6],[7,8,9]], 0)

array([[1, 0, 0],
       [4, 5, 0],
       [7, 8, 9]])

In [52]:
np.tril([[1,2,3],[4,5,6],[7,8,9]], -1)

array([[0, 0, 0],
       [4, 0, 0],
       [7, 8, 0]])

In [49]:
#return Upper triangle of an array.

In [50]:
np.triu([[1,2,3],[4,5,6],[7,8,9],[10,11,12]], 1)

array([[0, 2, 3],
       [0, 0, 6],
       [0, 0, 0],
       [0, 0, 0]])

# Random number generation

In [53]:
print("Random number generation (from Uniform distribution)")
print(np.random.rand(2,3)) # 2 by 3 matrix with random numbers ranging from 0 to 1, Note no Tuple is necessary 

Random number generation (from Uniform distribution)
[[0.77408936 0.00877014 0.43501638]
 [0.67264491 0.51696321 0.45638901]]


In [54]:
print("Numbers from Normal distribution with zero mean and standard deviation 1 i.e. standard normal")
print(np.random.randn(4,3))  # randn- always form data in normal distribution

Numbers from Normal distribution with zero mean and standard deviation 1 i.e. standard normal
[[ 1.22903437  0.91091026  0.62176986]
 [ 0.72062017 -1.3555718   0.8840624 ]
 [-0.90938351  1.95503974  1.43853432]
 [-1.44057418  1.34193418  0.55122094]]


In [55]:
print("Random integer vector:",np.random.randint(1,10)) #randint (low, high, # of samples to be drawn)
print ("\nRandom integer matrix")


Random integer vector: 8

Random integer matrix


In [56]:
print(np.random.randint(1,100,(4,4))) #randint (low, high, # of samples to be drawn in a tuple to form a matrix)
print("\n20 samples drawn from a dice throw:",np.random.randint(1,7,20)) # 20 samples drawn from a dice throw

[[99 21 22 51]
 [69 87 44 80]
 [94 96 42 60]
 [47 95  1 99]]

20 samples drawn from a dice throw: [5 2 1 3 6 2 4 1 2 2 2 4 2 6 5 6 2 4 2 2]


# Reshaping

In [57]:
from numpy.random import randint as ri

In [58]:
ri(1,100,30).reshape(15,2)

array([[33, 85],
       [52, 61],
       [16, 32],
       [77, 88],
       [21,  9],
       [21, 29],
       [28, 25],
       [22, 21],
       [14, 25],
       [30, 64],
       [24, 72],
       [53, 69],
       [47, 34],
       [41, 21],
       [49, 21]])

In [59]:

a = ri(1,100,30)
b = a.reshape(2,3,5)
c = a.reshape(6,-19878)
c

array([[90, 68,  7, 97, 30],
       [10, 83, 95, 89, 52],
       [14, 61, 98, 33, 83],
       [98, 56, 69,  9, 63],
       [ 1, 29, 33, 89,  1],
       [96,  1, 41, 75,  2]])

In [60]:
print ("Shape of a:", a.shape)
print ("Shape of b:", b.shape)
print ("Shape of c:", c.shape)


Shape of a: (30,)
Shape of b: (2, 3, 5)
Shape of c: (6, 5)


In [61]:
print("\na looks like\n",'-'*20,"\n",a,"\n",'-'*20)
print("\nb looks like\n",'-'*20,"\n",b,"\n",'-'*20)
print("\nc looks like\n",'-'*20,"\n",c,"\n",'-'*20)



a looks like
 -------------------- 
 [90 68  7 97 30 10 83 95 89 52 14 61 98 33 83 98 56 69  9 63  1 29 33 89
  1 96  1 41 75  2] 
 --------------------

b looks like
 -------------------- 
 [[[90 68  7 97 30]
  [10 83 95 89 52]
  [14 61 98 33 83]]

 [[98 56 69  9 63]
  [ 1 29 33 89  1]
  [96  1 41 75  2]]] 
 --------------------

c looks like
 -------------------- 
 [[90 68  7 97 30]
 [10 83 95 89 52]
 [14 61 98 33 83]
 [98 56 69  9 63]
 [ 1 29 33 89  1]
 [96  1 41 75  2]] 
 --------------------


In [62]:
A = ri(1,100,10) # Vector of random interegrs
print("\nVector of random integers\n",'-'*50,"\n",A)
print("\nHere is the sorted vector\n",'-'*50,"\n",np.sort(A))



Vector of random integers
 -------------------------------------------------- 
 [24 79 35  6 50 73 83 90 22 18]

Here is the sorted vector
 -------------------------------------------------- 
 [ 6 18 22 24 35 50 73 79 83 90]


In [63]:
M = ri(1,100,25).reshape(5,5) # Matrix of random interegrs
#print("\nHere is the sorted matrix along each row\n",'-'*50,"\n",np.sort(M, kind='mergesort')) # Default axis =1
print("\nHere is the sorted matrix along each column\n",'-'*50,"\n",np.sort(M, axis=1, kind='mergesort'))
M


Here is the sorted matrix along each column
 -------------------------------------------------- 
 [[ 2 59 72 86 89]
 [18 55 70 93 97]
 [32 32 47 61 89]
 [17 28 62 69 93]
 [ 4 24 42 53 83]]


array([[ 2, 59, 72, 89, 86],
       [18, 70, 55, 97, 93],
       [61, 32, 89, 32, 47],
       [69, 17, 93, 62, 28],
       [ 4, 53, 42, 24, 83]])

In [65]:
np.sort(M, axis=0, kind='mergesort') # row wise

array([[ 2, 17, 42, 24, 28],
       [ 4, 32, 55, 32, 47],
       [18, 53, 72, 62, 83],
       [61, 59, 89, 89, 86],
       [69, 70, 93, 97, 93]])

In [69]:
print("Max of a:", M.max())


Max of a: 97


In [70]:
M

array([[ 2, 59, 72, 89, 86],
       [18, 70, 55, 97, 93],
       [61, 32, 89, 32, 47],
       [69, 17, 93, 62, 28],
       [ 4, 53, 42, 24, 83]])

In [71]:
print("Max of a location:", M.argmax(axis= 1 ))


Max of a location: [3 3 2 2 4]


In [72]:
M.argmax()

8

# Indexing and slicing

In [2]:
import numpy as np
arr = np.arange(0,11)
print("Array:",arr)


Array: [ 0  1  2  3  4  5  6  7  8  9 10]


In [3]:
print("Element at 7th index is:", arr[7])


Element at 7th index is: 7


In [4]:
print("Elements from 3rd to 5th index are:", arr[3:6:2])


Elements from 3rd to 5th index are: [3 5]


In [5]:
print("Elements up to 4th index are:", arr[:4])
arr

Elements up to 4th index are: [0 1 2 3]


array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [6]:
print("Elements from last backwards are:", arr[-1:7:-1])


Elements from last backwards are: [10  9  8]


In [7]:
print("3 Elements from last backwards are:", arr[-1:-6:2])


3 Elements from last backwards are: []


In [8]:
arr = np.arange(0,21,2)
print("New array:",arr)


New array: [ 0  2  4  6  8 10 12 14 16 18 20]


In [9]:
print("Elements at 2nd, 4th, and 9th index are:", arr[[2,4,9]]) # Pass a list as a index to subset

Elements at 2nd, 4th, and 9th index are: [ 4  8 18]


In [12]:
from numpy.random import randint as ri
import numpy as np 
mat = np.array(ri(10,100,15)).reshape(3,5)
print("Matrix of random 2-digit numbers\n--------------------------------\n",mat)
mat[1:4,3:5]


Matrix of random 2-digit numbers
--------------------------------
 [[44 17 13 19 78]
 [64 13 84 75 78]
 [95 86 64 31 15]]


array([[75, 78],
       [31, 15]])

In [17]:
mat[0:3,[1,3]]

array([[17, 19],
       [13, 75],
       [86, 31]])

In [18]:
mat[0:3,[1,4]]

array([[17, 78],
       [13, 78],
       [86, 15]])

In [19]:
print("\nDouble bracket indexing\n------------------------")
print("Element in row index 1 and column index 2:", mat[1][1])
mat


Double bracket indexing
------------------------
Element in row index 1 and column index 2: 13


array([[44, 17, 13, 19, 78],
       [64, 13, 84, 75, 78],
       [95, 86, 64, 31, 15]])

In [20]:
print("\nSingle bracket with comma indexing\n----------------------------------")
print("Element in row index 1 and column index 2:", mat[1,2])
print("\nRow or column extract\n----------------------")



Single bracket with comma indexing
----------------------------------
Element in row index 1 and column index 2: 84

Row or column extract
----------------------


In [21]:
print("Entire row at index 2:", mat[2])
print("Entire column at index 3:", mat[:,3])


Entire row at index 2: [95 86 64 31 15]
Entire column at index 3: [19 75 31]


In [22]:
print("\nSubsetting sub-matrices\n--------------------------")
print("Matrix with row indices 1 and 2 and column indices 3 and 4\n", mat[1:3,3:5])



Subsetting sub-matrices
--------------------------
Matrix with row indices 1 and 2 and column indices 3 and 4
 [[75 78]
 [31 15]]


In [23]:
print("Matrix with row indices 0 and 1 and column indices 1 and 3\n", mat[0:2,[1,3]])

Matrix with row indices 0 and 1 and column indices 1 and 3
 [[17 19]
 [13 75]]


# Subseting

In [24]:
mat = np.array(ri(10,100,15)).reshape(3,5)
print("Matrix of random 2-digit numbers\n--------------------------------\n",mat)
mat>50

Matrix of random 2-digit numbers
--------------------------------
 [[17 70 57 96 18]
 [22 30 42 35 31]
 [34 76 87 99 82]]


array([[False,  True,  True,  True, False],
       [False, False, False, False, False],
       [False,  True,  True,  True,  True]])

In [25]:
print ("Elements greater than 50\n", mat[mat>50])

Elements greater than 50
 [70 57 96 76 87 99 82]


# Slicing

In [26]:
mat = np.array([[11,12,13],[21,22,23],[31,32,33]])
print("Original matrix")
print(mat)


Original matrix
[[11 12 13]
 [21 22 23]
 [31 32 33]]


In [27]:
mat_slice = mat[:2,:2]
print ("\nSliced matrix")
print(mat_slice)
print ("\nChange the sliced matrix")


Sliced matrix
[[11 12]
 [21 22]]

Change the sliced matrix


In [28]:
mat_slice[0,0] = 1000
print (mat_slice)

[[1000   12]
 [  21   22]]


In [29]:
print("\nBut the original matrix? WHOA! It got changed too!")
print(mat)



But the original matrix? WHOA! It got changed too!
[[1000   12   13]
 [  21   22   23]
 [  31   32   33]]


In [30]:
# Little different way to create a copy of the slixed matrix
print ("\nDoing it again little differently now...\n")
mat = np.array([[11,12,13],[21,22,23],[31,32,33]])
print("Original matrix")
print(mat)



Doing it again little differently now...

Original matrix
[[11 12 13]
 [21 22 23]
 [31 32 33]]


In [31]:
mat_slice = np.array(mat[:2,:2]) # Notice the np.array command to create a new array not just slicing
print ("\nSliced matrix")
print(mat_slice)



Sliced matrix
[[11 12]
 [21 22]]


In [32]:
print ("\nChange the sliced matrix")
mat_slice[0,0] = 1000
print (mat_slice)



Change the sliced matrix
[[1000   12]
 [  21   22]]


In [33]:
print("\nBut the original matrix? NO CHANGE this time:)")
print(mat)


But the original matrix? NO CHANGE this time:)
[[11 12 13]
 [21 22 23]
 [31 32 33]]


# Universal Functions

In [34]:
mat1 = np.array(ri(1,10,9)).reshape(3,3)
mat2 = np.array(ri(1,10,9)).reshape(3,3)
print("\n1st Matrix of random single-digit numbers\n----------------------------------------\n",mat1)
print("\n2nd Matrix of random single-digit numbers\n----------------------------------------\n",mat2)



1st Matrix of random single-digit numbers
----------------------------------------
 [[3 5 1]
 [1 2 1]
 [8 3 8]]

2nd Matrix of random single-digit numbers
----------------------------------------
 [[4 8 1]
 [3 7 5]
 [2 5 2]]


In [36]:
mat1*mat2   # multiply element wise

array([[12, 40,  1],
       [ 3, 14,  5],
       [16, 15, 16]])

In [38]:
print("\nAddition\n------------------\n", mat1+mat2)


Addition
------------------
 [[ 7 13  2]
 [ 4  9  6]
 [10  8 10]]


In [39]:

print("\nMultiplication\n------------------\n", mat1@mat2) # matrix ,ultiplication



Multiplication
------------------
 [[ 29  64  30]
 [ 12  27  13]
 [ 57 125  39]]


In [40]:
print("\nDivision\n------------------\n", mat1/0)




Division
------------------
 [[inf inf inf]
 [inf inf inf]
 [inf inf inf]]


<ipython-input-40-ea15cab37cb9>:1: RuntimeWarning: divide by zero encountered in true_divide
  print("\nDivision\n------------------\n", mat1/0)


In [41]:
print("\nLineaer combination: 3*A - 2*B\n-----------------------------\n", 3*mat1-2*mat2)


Lineaer combination: 3*A - 2*B
-----------------------------
 [[ 1 -1  1]
 [-3 -8 -7]
 [20 -1 20]]


In [42]:
print("\nAddition of a scalar (100)\n-------------------------\n", 100+mat1)



Addition of a scalar (100)
-------------------------
 [[103 105 101]
 [101 102 101]
 [108 103 108]]


In [43]:
print("\nExponentiation, matrix cubed here\n----------------------------------------\n", mat1**3)
print("\nExponentiation, sq-root using pow function\n-------------------------------------------\n",pow(mat1,3))


Exponentiation, matrix cubed here
----------------------------------------
 [[ 27 125   1]
 [  1   8   1]
 [512  27 512]]

Exponentiation, sq-root using pow function
-------------------------------------------
 [[ 27 125   1]
 [  1   8   1]
 [512  27 512]]


# Broadcasting

In [44]:
#NumPy operations are usually done on pairs of arrays on an element-by-element basis. 
#In the simplest case, the two arrays must have exactly the same shape.
#NumPy’s broadcasting rule relaxes this constraint when the arrays’ shapes meet certain constraints. 
#When operating on two arrays, NumPy compares their shapes element-wise. It starts with the trailing 
#dimensions, and works its way forward. Two dimensions are compatible when
#they are equal, or one of them is 1

In [45]:
start = np.zeros((4,4))
start= start+100
start

array([[100., 100., 100., 100.],
       [100., 100., 100., 100.],
       [100., 100., 100., 100.],
       [100., 100., 100., 100.]])

In [46]:
# create a rank 1 ndarray with 3 values
add_rows = np.array([1, 0, 2,5])
print(add_rows)

[1 0 2 5]


In [47]:
y = start + add_rows  # add to each row of 'start' using broadcasting
print(y)

[[101. 100. 102. 105.]
 [101. 100. 102. 105.]
 [101. 100. 102. 105.]
 [101. 100. 102. 105.]]


In [48]:
# create an ndarray which is 4 x 1 to broadcast across columns
add_cols = np.array([[0,1,2,3]])
add_cols = add_cols.T
print(add_cols)

[[0]
 [1]
 [2]
 [3]]


In [49]:
# add to each column of 'start' using broadcasting
y = start + add_cols 
print(y)

[[100. 100. 100. 100.]
 [101. 101. 101. 101.]
 [102. 102. 102. 102.]
 [103. 103. 103. 103.]]


In [50]:
# this will just broadcast in both dimensions
add_scalar = np.array([100])  
print(start+y)

[[200. 200. 200. 200.]
 [201. 201. 201. 201.]
 [202. 202. 202. 202.]
 [203. 203. 203. 203.]]


# Array Math

In [51]:
mat1 = np.array(ri(1,10,9)).reshape(3,3)
mat2 = np.array(ri(1,10,9)).reshape(3,3)
print("\n1st Matrix of random single-digit numbers\n\n",mat1)
print("\n2nd Matrix of random single-digit numbers\n------------\n",mat2)



1st Matrix of random single-digit numbers

 [[7 4 1]
 [8 2 6]
 [7 4 1]]

2nd Matrix of random single-digit numbers
------------
 [[1 8 1]
 [1 4 3]
 [4 5 2]]


In [52]:
print("\nSq-root of 1st matrix using np\n------------------\n", np.sqrt(mat1))



Sq-root of 1st matrix using np
------------------
 [[2.64575131 2.         1.        ]
 [2.82842712 1.41421356 2.44948974]
 [2.64575131 2.         1.        ]]


In [53]:
print("\nExponential power of 1st matrix using np\n",'-'*50,"\n", np.exp(mat1))



Exponential power of 1st matrix using np
 -------------------------------------------------- 
 [[1.09663316e+03 5.45981500e+01 2.71828183e+00]
 [2.98095799e+03 7.38905610e+00 4.03428793e+02]
 [1.09663316e+03 5.45981500e+01 2.71828183e+00]]


In [54]:
print("\n10-base logarithm on 1st matrix using np\n",'-'*50,"\n", np.log10(mat1))
print(mat1)
print(mat2)


10-base logarithm on 1st matrix using np
 -------------------------------------------------- 
 [[0.84509804 0.60205999 0.        ]
 [0.90308999 0.30103    0.77815125]
 [0.84509804 0.60205999 0.        ]]
[[7 4 1]
 [8 2 6]
 [7 4 1]]
[[1 8 1]
 [1 4 3]
 [4 5 2]]


In [55]:
print("\nModulo reminder using np\n",'-'*50,"\n", np.fmod(mat1,mat2))
mat1%mat2


Modulo reminder using np
 -------------------------------------------------- 
 [[0 4 0]
 [0 2 0]
 [3 4 1]]


array([[0, 4, 0],
       [0, 2, 0],
       [3, 4, 1]], dtype=int32)

In [56]:
print("\nCombination of functions by shwoing exponetial decay of a sine wave\n",'-'*70)



Combination of functions by shwoing exponetial decay of a sine wave
 ----------------------------------------------------------------------


In [57]:
A = np.linspace(0,12*np.pi,1001)


In [58]:
A

array([ 0.        ,  0.03769911,  0.07539822, ..., 37.62371362,
       37.66141273, 37.69911184])